### ISSUE TITLE
Code Snippets - Syntax highlighting

### ISSUE THREAD

**Issue by theRemix** [AirshipCMS/angular-1.airshipcms.io#4]
Find and choose the best, most lightweight single library to perform syntax highlighting for code blocks.

**Comment by kellishouts** [comment]
If the docs need to be updated to document what was used/included for the project, please update the markdown docs.

**Comment by fobabett** [comment]
starting

**Comment by fobabett** [comment]
done

**Comment by kellishouts** [comment]
Can you adjust so that the large code blocks have a dark-grey (#333 -ish) background theme & the syntax highlighting adjusts accordingly?

**Comment by kellishouts** [comment]
Also adjust the style for the generic `<code>` selector:
```
code{
  font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace;
}
```

**Comment by kellishouts** [comment]
Also:
```
code, code > *, code > * > * {
    font-size: 0.8rem !important;
}
```

**Comment by kellishouts** [comment]
Also:
```
pre code{
    padding: 0;
}
```

**Comment by fobabett** [comment]
starting

**Comment by fobabett** [comment]
done
