### ISSUE TITLE
Modify Docs for `Angular 1`

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/angular-1.airshipcms.io#5]
In the near future, we plan to modify the cli so that any user can `airship serve` a site if the superadmin for the site turns on the setting for the site to be publicly servable by anyone (essentially open source).

I've modified the README and the docs to reflect this. I've been editing the README file directly in Github, and the contents of the CMS i put in a directory called `cms-content`, which I'm also directly editing in Github.

Review the changes to the README and the docs in cms-content.
Update the `angular-tutorial.md`. It feels like there is a missing step 5.
Update the `styling.md`. Is there a step for running the project missing?
If there are any "@fobabett" notes I left in there, can you fix? I think I removed all of them, though I'm not 100% sure.
Once the markdown docs are updated, I've been updating the live site version by inspecting the html version of the markdown doc and copying the content into Airship CMS. Can you update the CMS with the newest versions of the markdown docs? Copying the entire `<article>` should be fine, except for the README/root page, where the top header and description are in separate fields in the CMS.

![screen shot 2017-07-24 at 1 59 18 pm](https://user-images.githubusercontent.com/1865400/28549791-5c316874-7078-11e7-8dfb-7f9d5379ab24.png)

Also, in the CMS, delete all the link icons: ![screen shot 2017-07-24 at 2 01 45 pm](https://user-images.githubusercontent.com/1865400/28549844-a5e38a38-7078-11e7-9d1e-d53d953e2d39.png) I just didn't get around to it.

Track your time! This is separate from the initial chunk of work. You might need to make a new "project" tag in Toggl. You can name it "OSS" for all the OSS project stuff.

**Comment by fobabett** [comment]
starting

**Comment by fobabett** [comment]
done
